name: Build application
on: workflow_dispatch

env:
  N8N_VERSION: latest
  organization: cloud-for-you
  project: n8n

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - linux/amd64
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Set cache name
        id: cache-name
        run: |
          echo "cache-name=${{ env.project }}-cache-${{ matrix.platform }}" | sed 's:/:-:g' >> $GITHUB_OUTPUT
      - name: Log in to Red Hat Registry
        uses: docker/login-action@v2
        with:
          registry: registry.redhat.io
          username: ${{ secrets.REDHAT_REGISTRY_USERNAME }}
          password: ${{ secrets.REDHAT_REGISTRY_PASSWORD }}
      - name: Docker build
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: ${{ matrix.platform }}
          tags: ${{ env.project }}:${{ github.ref_name }}
          cache-from: type=gha
          cache-to: type=local,dest=/tmp/${{ env.project }}-cache,mode=max
          build-args: |
            N8N_VERSION=${{ env.N8N_VERSION }}
            TARGETPLATFORM=${{ matrix.platform }}
      - name: Upload cache
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.cache-name.outputs.cache-name }}
          path: /tmp/${{ env.project }}-cache
          if-no-files-found: error
          retention-days: 1

  push:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Download cache
        uses: actions/download-artifact@v4
        with:
          path: /tmp/${{ env.project }}-cache
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            quay.io/${{ env.organization }}/${{ env.project }}
          tags: |
            type=raw,value=latest
      - name: Log in to Red Hat Registry
        uses: docker/login-action@v2
        with:
          registry: registry.redhat.io
          username: ${{ secrets.REDHAT_REGISTRY_USERNAME }}
          password: ${{ secrets.REDHAT_REGISTRY_PASSWORD }}
      - name: Login to QUAY.IO
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}
      - name: Docker push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: |
            linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=gha,mode=max

